### ISSUE TITLE
Error when launching Greta demo

### ISSUE THREAD

**Issue by ThomasJanssoone** [AgentsUnited/demonstrator#13]
Hello,

first of all, thank you for your work and for sharing this demonstrator.

I wanted to test it to see if it can fit our needs to perform research studies with Virtual Agent.
I installed the system following the `Readme` instructions
Yet, at `Run Greta` step,  I have an issue I do not understand.
When I run `java -jar Modular.jar`, I have the UI panel
Then, loading the ` Council of Coaches - TechnicalDemonstrator.xml.` open the 14 small screens, I can see quickly something on then. Immediately after, the system crashes with the following error : 

```
Loading library C:/Articulabo/21_system/AgentsUnited/demonstrator/greta/bin/Player/Lib/External/Win64/Libs\Plugin_CgProgramManager
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  EXCEPTION_UNCAUGHT_CXX_EXCEPTION (0xe06d7363) at pc=0x00007fffeae94ed9, pid=24328, tid=0x0000000000008568
#
# JRE version: Java(TM) SE Runtime Environment (8.0_211-b12) (build 1.8.0_211-b12)
# Java VM: Java HotSpot(TM) 64-Bit Server VM (25.211-b12 mixed mode windows-amd64 compressed oops)
# Problematic frame:
# C  [KERNELBASE.dll+0x34ed9]
#
# Failed to write core dump. Minidumps are not enabled by default on client versions of Windows
#
# An error report file with more information is saved as:
# C:\Articulabo\21_system\AgentsUnited\demonstrator\greta\bin\hs_err_pid24328.log
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.java.com/bugreport/crash.jsp
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#
```
I can share the full log file if needed

I already checked my Java version :
```
> java -version
java version "1.8.0_211"
Java(TM) SE Runtime Environment (build 1.8.0_211-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.211-b12, mixed mode)
```
and downgrade unity to `version 2017.4.24f1`

Do you have an idea of what could cause this error?

Thanks in advance

Best

Thomas

**Comment by hopdenakker** [comment]
Hi Thomas, thanks for your interest in the demonstrator. I can't help you with this technical issue myself, but I'll make sure to notify some people who might!

**Comment by ThomasJanssoone** [comment]
Hello, 

just to let you know that I figure out the reason for this error: a bad ant installation with a different version 🥲 

Best

**Comment by hopdenakker** [comment]
Thanks for reporting this and for reporting the solution as well @ThomasJanssoone
