### ISSUE TITLE
Create folder with demo WOOL scripts that can be added to WOOL Web Service

### ISSUE THREAD

**Issue by tbeinema** [AgentsUnited/demonstrator#9]
The demo WOOL scripts should be added to the resources folder in the WOOL Web Service. It is probably best to also upload these files to the demonstrator repo (as they do not really belong in the WOOL repo). This would allow others to run the demo on their own devices.

**Comment by hopdenakker** [comment]
Yes, they should not be added to the WOOL repository 👍
